india_places = {
    "taj_mahal": {
        "name": "Taj Mahal",
        "tags": ["history", "architecture", "unesco"],
        "cluster": "Agra",
        "state": "Uttar Pradesh",
        "lat": 27.1751,
        "lon": 78.0421,
        "image": "https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "The Taj Mahal is an ivory-white marble mausoleum on the south bank of the Yamuna river in the Indian city of Agra.",
        "year_built": "1632-1653",
        "category": "Mausoleum",
        "tickets": {"indian": 50, "student": 25, "foreigner": 1300},
        "best_time": "October to March",
        "timings": "Sunrise to sunset"
    },

    "gateway_of_india": {
        "name": "Gateway of India",
        "tags": ["colonial", "architecture"],
        "cluster": "Colaba",
        "state": "Maharashtra",
        "lat": 18.9219,
        "lon": 72.8347,
        "image": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "The Gateway of India is an arch-monument built in the early twentieth century in the city of Mumbai.",
        "year_built": "1924",
        "category": "Monument",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0},
        "best_time": "November to February",
        "timings": "Open 24 hours"
    },

    "mysore_palace": {
        "name": "Mysore Palace",
        "tags": ["royal", "architecture"],
        "cluster": "Mysore",
        "state": "Karnataka",
        "lat": 12.3051,
        "lon": 76.6551,
        "image": "https://images.unsplash.com/photo-1659126574791-13313aa424bd?q=80&w=1332&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Mysore Palace is a historical palace and a royal residence at Mysore in the Indian State of Karnataka.",
        "year_built": "1897",
        "category": "Royal Palace",
        "tickets": {"indian": 40, "student": 20, "foreigner": 200},
        "best_time": "September to March",
        "timings": "10:00 AM - 5:30 PM"
    },

    "meenakshi_temple": {
        "name": "Meenakshi Amman Temple",
        "tags": ["religion", "architecture"],
        "cluster": "Madurai",
        "state": "Tamil Nadu",
        "lat": 9.9198,
        "lon": 78.1194,
        "image": "https://images.unsplash.com/photo-1689525508929-eb6b773b1fd2?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Historically significant Hindu temple located on the southern bank of the Vaigai River in Madurai.",
        "year_built": "12th Century",
        "category": "Temple",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0},
        "best_time": "October to March",
        "timings": "6:00 AM - 12:30 PM, 4:00 PM - 9:00 PM"
    },

    "hawa_mahal": {
        "name": "Hawa Mahal",
        "tags": ["palace", "architecture"],
        "cluster": "Pink City",
        "state": "Rajasthan",
        "lat": 26.9239,
        "lon": 75.8267,
        "image": "https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Hawa Mahal is a palace in Jaipur, India, constructed of red and pink sandstone.",
        "year_built": "1799",
        "category": "Palace",
        "tickets": {"indian": 50, "student": 20, "foreigner": 200},
        "best_time": "October to March",
        "timings": "9:00 AM - 5:00 PM"
    },

    "victoria_memorial": {
        "name": "Victoria Memorial",
        "tags": ["museum", "colonial"],
        "cluster": "Kolkata",
        "state": "West Bengal",
        "lat": 22.5448,
        "lon": 88.3426,
        "image": "https://images.unsplash.com/photo-1697817665440-f988c6d5080f?q=80&w=1047&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "Large marble building in Kolkata, built between 1906 and 1921 dedicated to the memory of Queen Victoria.",
        "year_built": "1921",
        "category": "Museum",
        "tickets": {"indian": 30, "student": 15, "foreigner": 200},
        "best_time": "October to February",
        "timings": "10:00 AM - 5:00 PM"
    },

    "golden_temple": {
        "name": "Harmandir Sahib (Golden Temple)",
        "tags": ["religion", "sikh"],
        "cluster": "Amritsar",
        "state": "Punjab",
        "lat": 31.6200,
        "lon": 74.8765,
        "image": "https://images.unsplash.com/photo-1587899765642-3f8e3ea67852?q=80&w=1331&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "The Golden Temple is a central religious place of the Sikhs, located in the city of Amritsar.",
        "year_built": "1604",
        "category": "Religious Site",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0},
        "best_time": "November to March",
        "timings": "24 hours"
    }
}

# Additional monuments for remaining states/UTs
additional_places = {
    "cellular_jail": {
        "name": "Cellular Jail",
        "cluster": "Port Blair",
        "state": "Andaman and Nicobar Islands",
        "tags": ["colonial", "history"],
        "lat": 11.6643,
        "lon": 92.7456,
        "image": "https://www.andamanisland.in/storage/blogs/61adfde97559a155_j5.jpg",
        "description": "A colonial prison used by the British to exile political prisoners, now a national memorial.",
        "year_built": "1906",
        "category": "Historical Monument",
        "tickets": {"indian": 10, "student": 5, "foreigner": 50}
    },
    "tirupati_balaji": {
        "name": "Tirupati Balaji (Venkateswara Temple)",
        "cluster": "Tirupati",
        "state": "Andhra Pradesh",
        "tags": ["religion", "pilgrimage"],
        "lat": 13.6833,
        "lon": 79.3500,
        "image": "https://c9admin.cottage9.com/uploads/2292/Our-Temples-Our-Heritage-Tirumala-Venkateshwara-Temple-Tirupati-Balaji.jpg",
        "description": "One of the most visited pilgrimage sites in India, dedicated to Lord Venkateswara.",
        "year_built": "Ancient",
        "category": "Temple",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "tawang_monastery": {
        "name": "Tawang Monastery",
        "cluster": "Tawang",
        "state": "Arunachal Pradesh",
        "tags": ["religion", "monastery"],
        "lat": 27.5860,
        "lon": 91.8668,
        "image": "https://s7ap1.scene7.com/is/image/incredibleindia/tawang-monastery-tawang-arunachal-pradesh-1-attr-hero?qlt=82&ts=1742169936069",
        "description": "One of the largest monasteries in India, important centre of Tibetan Buddhism.",
        "year_built": "17th Century",
        "category": "Monastery",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "kamakhya_temple": {
        "name": "Kamakhya Temple",
        "cluster": "Guwahati",
        "state": "Assam",
        "tags": ["religion", "history"],
        "lat": 26.1667,
        "lon": 91.7414,
        "image": "https://s7ap1.scene7.com/is/image/incredibleindia/kamakhya-temple-dispur-assam-2-attr-hero?qlt=82&ts=1742179171313",
        "description": "An important Hindu temple and pilgrimage site dedicated to the mother goddess Kamakhya.",
        "year_built": "Ancient",
        "category": "Temple",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "mahabodhi_temple": {
        "name": "Mahabodhi Temple",
        "cluster": "Bodh Gaya",
        "state": "Bihar",
        "tags": ["buddhism", "unesco"],
        "lat": 24.6956,
        "lon": 84.9911,
        "image": "https://www.buddhisttourism.online/assets/images/mahabodhi-banner3.webp",
        "description": "The Mahabodhi Temple is the location where Buddha is said to have attained enlightenment.",
        "year_built": "5th Century",
        "category": "Temple",
        "tickets": {"indian": 20, "student": 10, "foreigner": 200}
    },
    "rock_garden": {
        "name": "Rock Garden",
        "cluster": "Chandigarh",
        "state": "Chandigarh",
        "tags": ["art", "garden"],
        "lat": 30.7333,
        "lon": 76.7794,
        "image": "https://www.allgudthings.com/wp-content/uploads/2019/04/rock-garden-chandigarh_edited-1024x683.jpg",
        "description": "A sculpture garden created from industrial & urban waste by Nek Chand.",
        "year_built": "1957",
        "category": "Garden",
        "tickets": {"indian": 20, "student": 10, "foreigner": 50}
    },
    "dantewada_bhoramdeo": {
        "name": "Bhoramdeo Temple",
        "cluster": "Dantewada",
        "state": "Chhattisgarh",
        "tags": ["history", "temple"],
        "lat": 19.6075,
        "lon": 81.9211,
        "image": "https://www.mytourplans.com/storage/ck/130623025351-khajuraho-dulhadeo-2010-1.jpg",
        "description": "An ancient temple complex sometimes called the 'Khajuraho of Chhattisgarh'.",
        "year_built": "11th Century",
        "category": "Temple",
        "tickets": {"indian": 10, "student": 5, "foreigner": 50}
    },
    "diu_fort": {
        "name": "Diu Fort",
        "cluster": "Diu",
        "state": "Dadra and Nagar Haveli and Daman and Diu",
        "tags": ["colonial", "fort"],
        "lat": 20.7147,
        "lon": 70.9906,
        "image": "https://makeithappen.co.in/wp-content/uploads/2021/12/Diu-Fort-Heritage-Walk-Make-It-Happen.jpg",
        "description": "A Portuguese-built sea fort guarding the coast of Diu Island.",
        "year_built": "16th Century",
        "category": "Fort",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "deoghar_baidyanath": {
        "name": "Baidyanath Temple",
        "cluster": "Deoghar",
        "state": "Jharkhand",
        "tags": ["religion", "pilgrimage"],
        "lat": 24.1910,
        "lon": 86.6909,
        "image": "https://behindeverytemple.org/wp-content/uploads/2020/09/vaidhyanath-dhaam.jpg",
        "description": "One of the twelve Jyotirlinga shrines of Lord Shiva and a prominent pilgrimage site.",
        "year_built": "Ancient",
        "category": "Temple",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "padmanabhaswamy": {
        "name": "Padmanabhaswamy Temple",
        "cluster": "Thiruvananthapuram",
        "state": "Kerala",
        "tags": ["religion", "architecture"],
        "lat": 8.4821,
        "lon": 76.9436,
        "image": "https://images.unsplash.com/photo-1644773182204-f0bf03cae0cb?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "description": "A historic Hindu temple dedicated to Lord Vishnu, famed for its architecture and vaults.",
        "year_built": "8th Century",
        "category": "Temple",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "leh_palace": {
        "name": "Leh Palace",
        "cluster": "Leh",
        "state": "Ladakh",
        "tags": ["palace", "history"],
        "lat": 34.1642,
        "lon": 77.5859,
        "image": "https://s7ap1.scene7.com/is/image/incredibleindia/leh-palace-leh-ladakh-2-musthead-hero?qlt=82&ts=1726668053114",
        "description": "A former royal palace overlooking Leh and the Indus valley, offering historic exhibits.",
        "year_built": "17th Century",
        "category": "Palace",
        "tickets": {"indian": 10, "student": 5, "foreigner": 50}
    },
    "kavaratti_lighthouse": {
        "name": "Kavaratti Island",
        "cluster": "Kavaratti",
        "state": "Lakshadweep",
        "tags": ["island", "beach"],
        "lat": 10.5699,
        "lon": 72.6366,
        "image": "https://www.holidaymonk.com/wp-content/uploads/2024/01/Kavaratti-Island-Lakshadweep-1.jpg",
        "description": "The capital island of Lakshadweep, known for lagoons and beaches.",
        "year_built": "—",
        "category": "Island",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "khajuraho_temples": {
        "name": "Khajuraho Temples",
        "cluster": "Khajuraho",
        "state": "Madhya Pradesh",
        "tags": ["history", "architecture", "unesco"],
        "lat": 24.8310,
        "lon": 79.9190,
        "image": "https://www.trinityairtravel.com/bblog/7980_second.jpg",
        "description": "Famous group of Hindu and Jain temples known for their nagara-style architecture and erotic sculptures.",
        "year_built": "950-1050",
        "category": "Temple Complex",
        "tickets": {"indian": 40, "student": 20, "foreigner": 600}
    },
    "kangla_fort": {
        "name": "Kangla Fort",
        "cluster": "Imphal",
        "state": "Manipur",
        "tags": ["history", "fort"],
        "lat": 24.8170,
        "lon": 93.9460,
        "image": "https://s7ap1.scene7.com/is/image/incredibleindia/kangla-fort-imphal-manipur-1-attr-hero?qlt=82&ts=1742165496756",
        "description": "An important historic fort and cultural site in Manipur's capital.",
        "year_built": "Ancient",
        "category": "Fort",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "living_root_bridges": {
        "name": "Living Root Bridges",
        "cluster": "Cherrapunji",
        "state": "Meghalaya",
        "tags": ["nature", "heritage"],
        "lat": 25.2776,
        "lon": 91.7116,
        "image": "https://res.cloudinary.com/roundglass/image/upload/w_1200,ar_16:9,c_fill,g_face,f_auto/v1649766851/rg/collective/media/meghalaya-nongriat-double-decker-living-root-bridge-greenery-people-ashwin-ezhumalai-1649766850629.jpg",
        "description": "Unique bridges formed from the roots of rubber trees—an example of bioengineering by local communities.",
        "year_built": "Traditional",
        "category": "Living Heritage",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "dampa_reserved": {
        "name": "Vantawng Falls / Mizoram sights",
        "cluster": "Aizawl",
        "state": "Mizoram",
        "tags": ["nature"],
        "lat": 23.7271,
        "lon": 92.7176,
        "image": "https://knowledgeofindia.com/wp-content/uploads/2020/01/Tuirihiau-Waterfall-In-Mizoram.jpg",
        "description": "Natural scenic spots in Mizoram are popular for their beauty and cultural significance.",
        "year_built": "—",
        "category": "Natural Site",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "kohima_memorial": {
        "name": "Kohima War Cemetery",
        "cluster": "Kohima",
        "state": "Nagaland",
        "tags": ["memorial", "history"],
        "lat": 25.6667,
        "lon": 94.1167,
        "image": "https://chalohoppo.com/wp-content/uploads/2024/05/120.jpg",
        "description": "A war cemetery commemorating soldiers from WWII battles in the region.",
        "year_built": "1944",
        "category": "Memorial",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "konark_sun_temple": {
        "name": "Konark Sun Temple",
        "cluster": "Konark",
        "state": "Odisha",
        "tags": ["history", "unesco"],
        "lat": 19.8876,
        "lon": 86.0940,
        "image": "https://www.dailyartmagazine.com/wp-content/uploads/2024/06/Cover-Photo-768x464.jpg",
        "description": "A 13th-century Sun Temple known for its intricate stone carvings and chariot form.",
        "year_built": "13th Century",
        "category": "Temple",
        "tickets": {"indian": 40, "student": 20, "foreigner": 600}
    },
    "auroville": {
        "name": "Auroville / Sri Aurobindo Ashram",
        "cluster": "Puducherry",
        "state": "Puducherry",
        "tags": ["ashram", "community"],
        "lat": 11.6234,
        "lon": 79.7410,
        "image": "https://www.shutterstock.com/image-photo/arial-view-auroville-experimental-township-600nw-1967101996.jpg",
        "description": "A spiritual community and the Sri Aurobindo Ashram are important cultural sites in Puducherry.",
        "year_built": "20th Century",
        "category": "Spiritual Site",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "rumtek_monastery": {
        "name": "Rumtek Monastery",
        "cluster": "Gangtok",
        "state": "Sikkim",
        "tags": ["monastery", "buddhism"],
        "lat": 27.3300,
        "lon": 88.6075,
        "image": "https://upload.wikimedia.org/wikipedia/commons/e/e5/Vikramjit-Kakati-Rumtek.jpg",
        "description": "A major Tibetan Buddhist monastery and seat of the Karmapa.",
        "year_built": "20th Century",
        "category": "Monastery",
        "tickets": {"indian": 10, "student": 5, "foreigner": 50}
    },
    "charminar": {
        "name": "Charminar",
        "cluster": "Hyderabad",
        "state": "Telangana",
        "tags": ["monument", "historic"],
        "lat": 17.3616,
        "lon": 78.4747,
        "image": "https://backpackersunited.in/_next/image?url=https%3A%2F%2Fbpu-images-v1.s3.eu-north-1.amazonaws.com%2Fuploads%2F1721737943352_Charminar%206.jpg&w=1920&q=75",
        "description": "An iconic mosque and monument in the heart of Hyderabad built in 1591.",
        "year_built": "1591",
        "category": "Monument",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "ujjayanta_palace": {
        "name": "Ujjayanta Palace",
        "cluster": "Agartala",
        "state": "Tripura",
        "tags": ["palace", "museum"],
        "lat": 23.8315,
        "lon": 91.2868,
            "image": "https://avathioutdoors.gumlet.io/travelGuide/dev/agartala_P8037.jpg",
        "description": "A former royal palace now housing a state museum and cultural exhibitions.",
        "year_built": "20th Century",
        "category": "Palace",
        "tickets": {"indian": 10, "student": 5, "foreigner": 50}
    },
    "basilica_bom_jesus": {
        "name": "Basilica of Bom Jesus",
        "cluster": "Old Goa",
        "state": "Goa",
        "tags": ["colonial", "religion", "unesco"],
        "lat": 15.4979,
        "lon": 73.8278,
        "image": "https://www.tourmyindia.com/states/goa/image/basilica-of-bom-jesus-goa.webp",
        "description": "A 16th-century Jesuit basilica in Old Goa, housing the mortal remains of St. Francis Xavier.",
        "year_built": "1605",
        "category": "Church",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "statue_of_unity": {
        "name": "Statue of Unity",
        "cluster": "Kevadia",
        "state": "Gujarat",
        "tags": ["modern", "memorial"],
        "lat": 21.8380,
        "lon": 73.7191,
        "image": "https://www.gujarattourism.com/content/dam/gujrattourism/images/home_page/opti/SOU.jpg",
        "description": "The world's tallest statue, dedicated to Sardar Vallabhbhai Patel, set on the Narmada river.",
        "year_built": "2018",
        "category": "Monument",
        "tickets": {"indian": 150, "student": 75, "foreigner": 800}
    },
    "brahma_sarovar": {
        "name": "Brahma Sarovar",
        "cluster": "Kurukshetra",
        "state": "Haryana",
        "tags": ["religion", "history"],
        "lat": 29.9691,
        "lon": 76.8423,
        "image": "https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYTI2MjFhMDQwLWY0YzQtMTFlZi1iNWU1LTAxNGU1NjQ3MjgyZS5qcGc=",
        "description": "A sacred water tank in Kurukshetra associated with Vedic rituals and the Mahabharata.",
        "year_built": "Ancient",
        "category": "Religious Site",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "hadimba_temple": {
        "name": "Hadimba Temple",
        "cluster": "Manali",
        "state": "Himachal Pradesh",
        "tags": ["temple", "architecture"],
        "lat": 32.2432,
        "lon": 77.1887,
        "image": "https://www.tourmyholiday.com/pdf/1696233741hidimba-devi-temple1.png",
        "description": "A 16th-century wooden temple dedicated to Hidimbi Devi, set amid cedar forests in Manali.",
        "year_built": "1553",
        "category": "Temple",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "vaishno_devi": {
        "name": "Vaishno Devi Shrine",
        "cluster": "Katra",
        "state": "Jammu and Kashmir",
        "tags": ["pilgrimage", "religion"],
        "lat": 33.0499,
        "lon": 74.9558,
        "image": "https://www.amritara.co.in/_next/image?url=https%3A%2F%2Famritaracms.cinuniverse.com%2Fimg%2Fpost%2Fimage_2024-11-29-10-36-16_6749992066923.jpg&w=1920&q=75",
        "description": "A major Hindu pilgrimage site located in the Trikuta Mountains, visited by millions each year.",
        "year_built": "Ancient",
        "category": "Pilgrimage Site",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    },
    "badrinath": {
        "name": "Badrinath Temple",
        "cluster": "Badrinath",
        "state": "Uttarakhand",
        "tags": ["pilgrimage", "religion"],
        "lat": 30.7433,
        "lon": 79.4936,
        "image": "https://www.chardhamplan.com/images/Badrinath-place-to-visit.png",
        "description": "One of the Char Dham pilgrimage sites, dedicated to Lord Vishnu.",
        "year_built": "Ancient",
        "category": "Temple",
        "tickets": {"indian": 0, "student": 0, "foreigner": 0}
    }
}

# merge additional places into existing india_places
for k, v in additional_places.items():
    if k not in india_places:
        india_places[k] = v
